easyNote/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('postit/', include('postit.urls')),
    path('', RedirectView.as_view(url = "/postit/")),
]

postit/urls.py
from django.urls import path
from . import views

app_name = 'postit'

urlpatterns = [
    path('', views.IndexListView.as_view(), name = 'index'),
    path('add_note', views.add_note, name = 'add_note'),
    path('del_all', views.del_all, name = "del_all"),
    path('mark_all', views.mark_all, name = "mark_all"),
    path('unmark_all', views.unmark_all, name = "unmark_all"),
    path('update_note', views.update_note, name = "update_note"),
    path('delete_note/<int:id>', views.delete_note, name = 'delete_note'),
    path('mark_note/<int:id>', views.mark_note, name = 'mark_note'),
]

postit/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Note (models.Model):
    alias = models.CharField(max_length = 255)
    note = models.CharField(max_length = 255)
    date_posted = models.DateField(default = timezone.now)
    state = (
        ('m', 'marked'),
        ('u', 'unmarked'),
    )
    status = models.CharField(max_length = 1, choices = state, default = 'u')

    def __str__(self):
        return self.alias

postit/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import ListView
from postit.models import Note
from django.views import View

# Create your views here.

class IndexListView(ListView):
    model = Note
    template_name = 'postit/index.html'
    context_object_name = 'notes'

    def get_queryset(self):
        return Note.objects.all().order_by('-id')

def add_note(request):
    if request.method == 'POST':
        note = request.POST.get('note')
        alias = request.POST.get('alias')
        #create new Object
        note = Note(
            alias = alias,
            note = note
        )
        note.save()
        return redirect('postit:index')

def mark_note(request, id):
    
    note = get_object_or_404(Note, id=id)
    
    if note.status == 'm':
        note.status = 'u'
    else:
        note.status = 'm'
    
    note.save()
    return redirect('postit:index')

def delete_note(request, id):
    note = get_object_or_404(Note, id=id)
    note.delete()
    return redirect('postit:index')


def update_note(request):
    if request.method == "POST":
        alias = request.POST.get('alias-edit')
        note = request.POST.get('note-edit')
        id = request.POST.get('note-id')
        note_obj = get_object_or_404(Note, id=id)
        note_obj.alias = alias
        note_obj.note = note
        note_obj.save();
        return redirect('postit:index')


#------------------------------------------------------------
#------Not yet tested
#------------------------------------------------------------


def del_all(request):
    notes = Note.objects.all()
    for i in notes:
        i.delete()
    return redirect('postit:index')

def mark_all(request):
    notes = Note.objects.all()
    for i in notes:
        i.status = 'm'
        i.save()
    return redirect('postit:index')

def unmark_all(request):
    notes = Note.objects.all()
    for i in notes:
        i.status = 'u'
        i.save()
    return redirect('postit:index')

postit/templates/postit/base.html
<!DOCTYPE html>
<html>
    {%load static%}
    <head>
        <title>{%block title%}{%endblock%}</title>
        <link rel = "stylesheet" href = "{% static 'postit/fontAwesome/css/all.min.css' %}">
        <link rel = "stylesheet" href = "{% static 'postit/style.css'%}">
        <link rel = "stylesheet" href = "">
        <meta name = "author" content = "Ayotunde Okunubi">
        {%block other_header_stuff%}
        {%endblock%}
    </head>
    <body>

        <div class = "panel-wrapper" style = "display: none" id = "editPanel">
            <span class = "fas fa-times cancel-btn" style = "background-color:lightgrey;padding:10px;border-radius:40%;position:absolute;top:0;right:5%;" id = "edit-cancel-btn"></span>
            <div class = "edit-panel">
                <form method = "POST" action = "{% url 'postit:update_note' %}">
                    {%csrf_token%}
                    <input type = "text" placeholder = "Alias" name = "alias-edit" required>
                    <input type = "text" placeholder = "Description" name = "note-edit" required><br><br>
                    <input type = "hidden" id = "note-id" name = "note-id">
                    <button type = "submit" style = "">Update Note</button>
                </form>
            </div>
        </div>

        <div class = "panel-wrapper" style = "display: none" id = "addPanel">
            <span class = "fas fa-times cancel-btn" style = "background-color:lightgrey;padding:10px;border-radius:40%;position:absolute;top:0;right:5%;" id = "cancel-btn"></span>
            <div class = "add-panel">
                <form method = "POST" action = "{% url 'postit:add_note' %}">
                    {%csrf_token%}
                    <input type = "text" placeholder = "Alias" name = "alias" required>
                    <input type = "text" placeholder = "Description" name = "note" required><br><br>
                    <button type = "submit" style = "">Add Note</button>
                </form>
            </div>
        </div>

        <div class = "row">
            <div>
            </div>

            <div style = "">
                <button class = "new-btn" id = "add-btn"><i class = "fas fa-plus"></i></button>
            {% block content %}
            {% endblock %}                
            </div>

            <div>
            </div>

        </div>

        <script src = ""></script>
        <script>
            const add_btn = document.querySelector("#add-btn");
            const cancel_btn = document.querySelector("#cancel-btn");
            const edit_cancel_btn = document.querySelector("#edit-cancel-btn");
            const addPanel = document.querySelector("#addPanel")
            const editPanel = document.querySelector("#editPanel")

            edit_cancel_btn.onclick = function(){
                editPanel.style.display = "none";
            }

            cancel_btn.onclick = function(){
                addPanel.style.display = "none";
            }
            add_btn.onclick = function(){
                addPanel.style.display = "block";

            }
        </script>
        {%block otherJS%}
        {%endblock%}
    </body>
</html>

postit/templates/postit/index.html
{% extends 'postit/base.html'%}

{%block title%}
Home
{%endblock%}

{%block content%}
<div style = "margin-top:10px;">
{% for note in notes%}
<div style = "background:lightgrey;">
    <div style = "padding:10px;margin-bottom:5px;" id = "main-{{note.id}}" onclick = "openDetail('detail-{{note.id}}')">
        <div>
            <span {% if note.status == 'm'%} style = "text-decoration:line-through;font-weight:bold;" {% endif %}>{{note.alias}}</span>
            <a href = "{% url 'postit:delete_note' note.id%}" class = ""><span class = "fas fa-trash menu-link" style = "float:right;"></span></a>
            <a href = "javascript:void(0)" class = "" id = "edit-{{note.id}}" data-alias = "{{note.alias}}" data-note = "{{note.note}}" onclick = "openEdit('edit-{{note.id}}')"><span class = "fas fa-pen menu-link" style = "float:right;"></span></a>
            <a href = "{% url 'postit:mark_note' note.id %}" class = ""><span class = "fas fa-check menu-link" style = "float:right;"></span></a>
        </div>
        <hr align = "left" style = "width:45%;border-bottom:.25px solid grey;">
    </div>
    <div style = "padding:10px;display:none;margin-bottom:5px;" id = "detail-{{note.id}}" class = "note-detail">
        <small>{{note.note}}</small>
    </div>
</div>
{% endfor %}
</div>

{%endblock%}

{% block otherJS%}
<script>
    const elements = document.querySelectorAll(".note-detail");

    //console.log(elements)

    function openDetail(elemId){
        for(let i=0; i<elements.length; i++){
            elements[i].style.display = "none";
        }
        let element = document.getElementById(elemId);
        element.style.display = "block";

    }

    function openEdit(elemId){
        element = document.getElementById(elemId);
        console.log(element);
        const alias = element.dataset['alias'];
        const note = element.dataset['note'];
        let edit_alias_input = document.querySelector("input[name='alias-edit']");
        let edit_note_input = document.querySelector("input[name='note-edit']");
        edit_alias_input.value = alias;
        edit_note_input.value = note;
        editPanel.style.display = "block";
        const edit_note_id = document.querySelector("#note-id");
        note_id = elemId.replace('edit-', '');
        edit_note_id.value = note_id;
        console.log(edit_note_id);
    }
</script>
{% endblock %}